// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBldXHd9YvzNRYD7zhuBy-zDQLTKdRH33U',
    appId: '1:151076841218:web:6c666805e184b11c9a441b',
    messagingSenderId: '151076841218',
    projectId: 'sistempakarpajak',
    authDomain: 'sistempakarpajak.firebaseapp.com',
    storageBucket: 'sistempakarpajak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1fZ2N5hCaVWOU9HyPvvgS2jISfhNRm14',
    appId: '1:151076841218:android:94594e81f9d1c55b9a441b',
    messagingSenderId: '151076841218',
    projectId: 'sistempakarpajak',
    storageBucket: 'sistempakarpajak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxCti1ZQ69taGhluO1gZSXs-irPTkD20',
    appId: '1:151076841218:ios:0c6f901541717af89a441b',
    messagingSenderId: '151076841218',
    projectId: 'sistempakarpajak',
    storageBucket: 'sistempakarpajak.appspot.com',
    iosClientId: '151076841218-ngptr7q33qqif4i3q9bkrg2cdjt6c065.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemPakarPajak',
  );
}
